/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ngx-airtable.module';
class NgxAirtableModuleInjector extends import0.ɵNgModuleInjector<import1.NgxAirtableModule> {
  _NgxAirtableModule_0:import1.NgxAirtableModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.NgxAirtableModule {
    this._NgxAirtableModule_0 = new import1.NgxAirtableModule(this.parent.get(import1.NgxAirtableModule,(null as any)));
    return this._NgxAirtableModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.NgxAirtableModule)) { return this._NgxAirtableModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const NgxAirtableModuleNgFactory:import0.NgModuleFactory<import1.NgxAirtableModule> = new import0.NgModuleFactory<any>(NgxAirtableModuleInjector,import1.NgxAirtableModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovV2ViU3Rvcm1zL25neC1haXJ0YWJsZS9saWIvc3JjL25neC1haXJ0YWJsZS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovV2ViU3Rvcm1zL25neC1haXJ0YWJsZS9saWIvc3JjL25neC1haXJ0YWJsZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
